import type {
  ActivityItem,
  AiRule,
  Conversation,
  Guest,
  HotelProfile,
  Invoice,
  Issue,
  KnowledgeDoc,
  PlanTier,
  Room,
  StaffUser,
  Subscription,
  Task,
  Upsell,
  WaThread,
} from "./types";

export const hotel: HotelProfile = {
  name: "Hotel Mercier",
  legalName: "Hotel Mercier BV",
  stars: 4,
  rooms: 48,
  address: "Leopoldstraat 42",
  postcode: "2000",
  city: "Antwerp",
  country: "Belgium",
  timezone: "Europe/Brussels",
  currency: "€",
  phone: "+32 3 227 41 00",
  email: "reception@hotelmercier.be",
  website: "hotelmercier.be",
  bookingEngine: "hotelmercier.be/book",
  whatsappNumber: "+32 3 227 41 08",
  checkIn: "15:00",
  checkOut: "11:00",
  languages: ["Dutch", "French", "English", "German"],
  vatNumber: "BE 0784.512.339",
  description:
    "A 48-room townhouse hotel in the fashion district, five minutes from Antwerp Central. Courtyard-facing Deluxe rooms, a small spa and a breakfast room that opens at 07:00.",
};

export const staff: StaffUser[] = [
  {
    id: "u-jonas",
    name: "Jonas Verhaeghe",
    role: "manager",
    title: "General Manager",
    email: "jonas@hotelmercier.be",
    phone: "+32 478 20 11 46",
    initials: "JV",
    lastActive: "now",
    whatsapp: true,
  },
  {
    id: "u-amelie",
    name: "Amélie Duprez",
    role: "front-office",
    title: "Front Office Agent",
    email: "amelie@hotelmercier.be",
    phone: "+32 471 55 09 32",
    initials: "AD",
    lastActive: "2 min ago",
    whatsapp: true,
  },
  {
    id: "u-rosa",
    name: "Rosa Ferreira",
    role: "housekeeping",
    title: "Housekeeping Manager",
    email: "rosa@hotelmercier.be",
    phone: "+32 465 88 12 70",
    initials: "RF",
    lastActive: "14 min ago",
    whatsapp: true,
  },
  {
    id: "u-peter",
    name: "Peter Janssens",
    role: "maintenance",
    title: "Technical Manager",
    email: "peter@hotelmercier.be",
    phone: "+32 494 31 62 18",
    initials: "PJ",
    lastActive: "6 min ago",
    whatsapp: true,
  },
  {
    id: "u-thibault",
    name: "Thibault Mertens",
    role: "front-office",
    title: "Night Auditor",
    email: "thibault@hotelmercier.be",
    phone: "+32 472 14 88 03",
    initials: "TM",
    lastActive: "yesterday 23:40",
    whatsapp: false,
  },
];

export const cleaners = ["Maria Silva", "Inês Duarte", "Kadir Yılmaz", "Alina Popescu"];
export const technicians = ["Peter Janssens", "Milan Novák"];

export const guests: Record<string, Guest> = {
  bertrand: {
    id: "g-bertrand",
    name: "Clara Bertrand",
    room: "302",
    country: "France",
    language: "French",
    vip: false,
    previousStays: 2,
    tags: ["Quiet room", "Late riser"],
    reservation: {
      number: "MRC-48219",
      arrival: "16 Aug",
      departure: "19 Aug",
      nights: 3,
      adults: 2,
      children: 0,
      roomType: "Deluxe King",
      status: "In House",
      rate: "€189 / night",
    },
  },
  vos: {
    id: "g-vos",
    name: "Hendrik Vos",
    room: "205",
    country: "Netherlands",
    language: "Dutch",
    vip: false,
    previousStays: 0,
    tags: ["Business"],
    reservation: {
      number: "MRC-48244",
      arrival: "17 Aug",
      departure: "18 Aug",
      nights: 1,
      adults: 1,
      children: 0,
      roomType: "Courtyard Double",
      status: "In House",
      rate: "€154 / night",
    },
  },
  tanabe: {
    id: "g-tanabe",
    name: "Yuki Tanabe",
    room: "307",
    country: "Japan",
    language: "English",
    vip: true,
    previousStays: 5,
    tags: ["VIP", "Returning", "Prefers high floor"],
    reservation: {
      number: "MRC-48301",
      arrival: "18 Aug",
      departure: "22 Aug",
      nights: 4,
      adults: 2,
      children: 0,
      roomType: "Junior Suite",
      status: "Confirmed",
      rate: "€268 / night",
    },
  },
  marchetti: {
    id: "g-marchetti",
    name: "Sofia Marchetti",
    country: "Italy",
    language: "Italian",
    vip: false,
    previousStays: 0,
    tags: ["Prospective booking"],
    reservation: {
      number: "ENQ-9914",
      arrival: "22 Aug",
      departure: "24 Aug",
      nights: 2,
      adults: 2,
      children: 0,
      roomType: "Not selected",
      status: "Enquiry",
      rate: "—",
    },
  },
  haddad: {
    id: "g-haddad",
    name: "Nadia Haddad",
    room: "411",
    country: "Belgium",
    language: "French",
    vip: false,
    previousStays: 1,
    tags: ["Billing dispute"],
    reservation: {
      number: "MRC-47988",
      arrival: "12 Aug",
      departure: "15 Aug",
      nights: 3,
      adults: 2,
      children: 1,
      roomType: "Family Room",
      status: "Checked Out",
      rate: "€212 / night",
    },
  },
  okonkwo: {
    id: "g-okonkwo",
    name: "Grace Okonkwo",
    room: "401",
    country: "United Kingdom",
    language: "English",
    vip: false,
    previousStays: 0,
    tags: ["Early arrival 13:00"],
    reservation: {
      number: "MRC-48288",
      arrival: "18 Aug",
      departure: "20 Aug",
      nights: 2,
      adults: 2,
      children: 0,
      roomType: "Deluxe King",
      status: "Confirmed",
      rate: "€196 / night",
    },
  },
  weiss: {
    id: "g-weiss",
    name: "Daniel Weiss",
    room: "212",
    country: "Germany",
    language: "German",
    vip: false,
    previousStays: 3,
    tags: ["Breakfast included"],
    reservation: {
      number: "MRC-48190",
      arrival: "15 Aug",
      departure: "18 Aug",
      nights: 3,
      adults: 1,
      children: 0,
      roomType: "Courtyard Double",
      status: "In House",
      rate: "€148 / night",
    },
  },
  raghavan: {
    id: "g-raghavan",
    name: "Priya Raghavan",
    room: "208",
    country: "India",
    language: "English",
    vip: false,
    previousStays: 0,
    tags: ["Baby cot requested"],
    reservation: {
      number: "MRC-48297",
      arrival: "18 Aug",
      departure: "21 Aug",
      nights: 3,
      adults: 2,
      children: 1,
      roomType: "Family Room",
      status: "Confirmed",
      rate: "€224 / night",
    },
  },
  bakke: {
    id: "g-bakke",
    name: "Lars Bakke",
    room: "115",
    country: "Norway",
    language: "English",
    vip: false,
    previousStays: 0,
    tags: ["Lost property"],
    reservation: {
      number: "MRC-47902",
      arrival: "9 Aug",
      departure: "12 Aug",
      nights: 3,
      adults: 2,
      children: 0,
      roomType: "Deluxe King",
      status: "Checked Out",
      rate: "€182 / night",
    },
  },
  novak: {
    id: "g-novak",
    name: "Elena Novak",
    room: "310",
    country: "Slovenia",
    language: "English",
    vip: false,
    previousStays: 0,
    tags: ["Anniversary"],
    reservation: {
      number: "MRC-48277",
      arrival: "17 Aug",
      departure: "19 Aug",
      nights: 2,
      adults: 2,
      children: 0,
      roomType: "Junior Suite",
      status: "In House",
      rate: "€248 / night",
    },
  },
};

export const seedConversations: Conversation[] = [
  {
    id: "c-1",
    guest: guests.bertrand,
    stage: "in-house",
    channels: ["whatsapp"],
    primaryChannel: "whatsapp",
    aiStatus: "escalated",
    sentiment: "frustrated",
    subject: "Air conditioning in 302 not cooling",
    summary:
      "Third message about the air conditioning in 302. A maintenance ticket was opened at 09:14 and is still in progress. Guest is now asking for a room change or compensation — outside the AI's authority.",
    suggestedReply:
      "Madame Bertrand, I am very sorry the room is still warm. Our technician is working on the unit now. I can move you to room 310, a Junior Suite, at no extra cost — it is ready from 13:00. Would you like me to hold it for you?",
    knowledgeUsed: ["Room Change Policy.pdf", "Compensation Guidelines.docx"],
    upsellIdeas: [],
    taskIds: ["t-3"],
    escalation: {
      reason: "Compensation requested — outside AI authority",
      urgency: "High",
      suggested: "Offer complimentary upgrade to 310 rather than a rate reduction.",
      raisedAt: "09:52",
    },
    unread: 2,
    lastAt: "09:52",
    aiHandledCount: 4,
    messages: [
      {
        id: "m-1-1",
        author: "guest",
        channel: "whatsapp",
        at: "08:31",
        body: "Bonjour, the air conditioning in room 302 does not seem to be cooling. It was quite warm last night.",
      },
      {
        id: "m-1-2",
        author: "ai",
        channel: "whatsapp",
        at: "08:31",
        confidence: 0.94,
        body: "Good morning Madame Bertrand, I am sorry about that. I have passed room 302 to our technical team and set the fan to maximum from reception. Someone will be with you within the hour.",
        knowledge: ["Hotel Information — Climate Control.pdf"],
      },
      {
        id: "m-1-3",
        author: "system",
        channel: "internal",
        at: "08:32",
        body: "Maintenance ticket MT-114 created — Room 302, air conditioning not cooling. Sent to Peter Janssens on WhatsApp.",
      },
      {
        id: "m-1-4",
        author: "guest",
        channel: "whatsapp",
        at: "09:40",
        body: "It is now 09:40 and nobody has come. The room is 26 degrees. This is the second night we cannot sleep properly.",
      },
      {
        id: "m-1-5",
        author: "ai",
        channel: "whatsapp",
        at: "09:41",
        confidence: 0.71,
        body: "I understand, and I apologise. Our technician accepted the request at 09:20 and is working on the unit. I am flagging this to our duty manager right now.",
      },
      {
        id: "m-1-6",
        author: "guest",
        channel: "whatsapp",
        at: "09:52",
        body: "Either we change room or I would expect the second night to be reduced. Can I speak with the manager please?",
      },
      {
        id: "m-1-7",
        author: "system",
        channel: "internal",
        at: "09:52",
        body: "Escalated: guest requested a human and mentioned compensation. AI replies paused for this conversation.",
      },
    ],
  },
  {
    id: "c-2",
    guest: guests.marchetti,
    stage: "pre-arrival",
    channels: ["whatsapp"],
    primaryChannel: "whatsapp",
    aiStatus: "ai-handling",
    sentiment: "positive",
    subject: "Quiet room for two, Fri–Sun",
    summary:
      "Prospective guest looking for a quiet double, 22–24 Aug. AI checked live availability in Mews, presented two categories, recommended the courtyard-facing Deluxe King and offered breakfast. Waiting for the guest to continue on the booking engine.",
    suggestedReply:
      "I have held nothing yet — the rate is live until midnight. Shall I send you the direct link with breakfast already included?",
    knowledgeUsed: ["Room Categories.pdf", "Breakfast & Rates.csv", "Mews — live availability"],
    upsellIdeas: [
      { label: "Breakfast for 2, both mornings", value: "€52.00", reason: "Guest asked about breakfast timing" },
      { label: "Airport transfer, arrival 18:20", value: "€68.00", reason: "Flight details mentioned" },
    ],
    taskIds: [],
    unread: 0,
    lastAt: "09:47",
    aiHandledCount: 6,
    messages: [
      {
        id: "m-2-1",
        author: "guest",
        channel: "whatsapp",
        at: "09:38",
        body: "Hello! I need a quiet room for two adults from Friday to Sunday. Is anything available?",
      },
      {
        id: "m-2-2",
        author: "ai",
        channel: "whatsapp",
        at: "09:38",
        confidence: 0.97,
        body: "Hello Sofia. Friday 22 to Sunday 24 August, two adults — let me check what we have.",
      },
      {
        id: "m-2-3",
        author: "system",
        channel: "internal",
        at: "09:39",
        body: "Availability checked in Mews · 22–24 Aug · 2 adults · 11 rooms open across 3 categories.",
      },
      {
        id: "m-2-4",
        author: "ai",
        channel: "whatsapp",
        at: "09:39",
        confidence: 0.95,
        knowledge: ["Room Categories.pdf", "Mews — live availability"],
        body: "Two rooms suit you well:\n\nDeluxe King — €189/night\nCourtyard-facing, the quietest side of the house.\n\nJunior Suite — €235/night\nMore space with a separate sitting area.\n\nBecause you asked for quiet, I would recommend the Deluxe King. Would you like breakfast included (€13 per person)?",
        buttons: ["Book on hotel website", "Tell me about breakfast"],
      },
      {
        id: "m-2-5",
        author: "guest",
        channel: "whatsapp",
        at: "09:46",
        body: "Breakfast sounds good. What time is it served? And we land at 18:20 on Friday.",
      },
      {
        id: "m-2-6",
        author: "ai",
        channel: "whatsapp",
        at: "09:47",
        confidence: 0.96,
        knowledge: ["Hotel Policy — Breakfast.pdf"],
        body: "Breakfast is served 07:00–10:30 on weekdays and until 11:00 at weekends, in the courtyard room.\n\nAn 18:20 landing is comfortable — reception is staffed 24 hours. We also run a private transfer from the airport for €68 for two. Shall I add it to your quote?",
        buttons: ["Yes, add transfer", "Book on hotel website"],
      },
    ],
  },
  {
    id: "c-3",
    guest: guests.vos,
    stage: "in-house",
    channels: ["whatsapp"],
    primaryChannel: "whatsapp",
    aiStatus: "ai-handling",
    sentiment: "neutral",
    subject: "Late checkout request",
    summary:
      "Guest in 205 asked for a 15:00 checkout. Departure day is a high-occupancy arrival day, so the AI offered the chargeable 14:00 option per policy and is waiting for confirmation.",
    suggestedReply:
      "14:00 is possible today for €35. 15:00 I would need to check against arrivals — would 14:00 work for you?",
    knowledgeUsed: ["Hotel Policy — Check-out.pdf", "Upsells — Late Checkout.csv"],
    upsellIdeas: [{ label: "Late checkout until 14:00", value: "€35.00", reason: "Guest asked for 15:00" }],
    taskIds: ["t-1"],
    unread: 1,
    lastAt: "09:21",
    aiHandledCount: 3,
    messages: [
      {
        id: "m-3-1",
        author: "guest",
        channel: "whatsapp",
        at: "09:18",
        body: "Morning — my train is at 16:30, could I keep the room until 15:00?",
      },
      {
        id: "m-3-2",
        author: "ai",
        channel: "whatsapp",
        at: "09:19",
        confidence: 0.88,
        knowledge: ["Hotel Policy — Check-out.pdf"],
        body: "Good morning Mr Vos. Standard checkout is 11:00. We can hold the room until 14:00 for €35, and I have asked reception whether 15:00 is possible given today's arrivals. I will confirm within the hour.",
        buttons: ["14:00 for €35", "Wait for 15:00 answer"],
      },
      {
        id: "m-3-3",
        author: "guest",
        channel: "whatsapp",
        at: "09:21",
        body: "Let's see if 15:00 works first, thank you.",
      },
    ],
  },
  {
    id: "c-4",
    guest: guests.haddad,
    stage: "post-stay",
    channels: ["gmail", "whatsapp"],
    primaryChannel: "gmail",
    aiStatus: "escalated",
    sentiment: "urgent",
    subject: "Double charge on final invoice",
    summary:
      "Guest was charged twice for the city tax and once for a minibar item she says she did not take. Billing dispute — always escalated by policy. Draft credit note of €47.60 prepared, needs manager approval.",
    suggestedReply:
      "Madame Haddad, thank you for the detail. I have reviewed folio MRC-47988: the city tax was indeed posted twice and the minibar item was posted to the wrong room. I am issuing a credit of €47.60 to your card today; it appears within 3 working days.",
    knowledgeUsed: ["Billing & Refund Policy.pdf"],
    upsellIdeas: [],
    taskIds: ["t-6"],
    escalation: {
      reason: "Billing dispute — always escalate",
      urgency: "High",
      suggested: "Approve €47.60 credit note and reply from the manager's mailbox.",
      raisedAt: "08:05",
    },
    unread: 1,
    lastAt: "08:05",
    aiHandledCount: 1,
    messages: [
      {
        id: "m-4-1",
        author: "guest",
        channel: "gmail",
        at: "07:58",
        body: "Good morning,\n\nI checked out on 15 August and reviewing the invoice I see the city tax charged twice (€10.60 each) and €26.40 for minibar. We did not open the minibar. Could you please look into this?\n\nKind regards,\nNadia Haddad",
      },
      {
        id: "m-4-2",
        author: "ai",
        channel: "gmail",
        at: "07:59",
        confidence: 0.62,
        body: "Dear Madame Haddad, thank you for your message. Billing questions are reviewed by our team personally — I have passed your invoice to the manager on duty and you will hear back today.",
      },
      {
        id: "m-4-3",
        author: "system",
        channel: "internal",
        at: "08:05",
        body: "Escalated automatically: billing dispute. Folio pulled from PMS, duplicate city tax confirmed, minibar posting traced to room 401.",
      },
    ],
  },
  {
    id: "c-5",
    guest: guests.okonkwo,
    stage: "pre-arrival",
    channels: ["outlook"],
    primaryChannel: "outlook",
    aiStatus: "ai-handling",
    sentiment: "positive",
    subject: "Early arrival at 13:00 + parking",
    summary:
      "Arriving 13:00 today, asked about parking and luggage storage. AI confirmed the garage rate and passed the early arrival to housekeeping — room 401 has been prioritised.",
    suggestedReply: "Room 401 was released by housekeeping at 12:26 — shall I confirm it is ready for 13:00?",
    knowledgeUsed: ["Hotel Information — Parking.pdf", "Hotel Policy — Check-in.pdf"],
    upsellIdeas: [{ label: "Garage parking, 2 nights", value: "€36.00", reason: "Arriving by car" }],
    taskIds: ["t-2"],
    unread: 0,
    lastAt: "07:44",
    aiHandledCount: 4,
    messages: [
      {
        id: "m-5-1",
        author: "guest",
        channel: "outlook",
        at: "07:40",
        body: "Hello, we arrive around 13:00 today. Is the room likely to be ready, and do you have parking on site?",
      },
      {
        id: "m-5-2",
        author: "ai",
        channel: "outlook",
        at: "07:41",
        confidence: 0.93,
        knowledge: ["Hotel Information — Parking.pdf", "Hotel Policy — Check-in.pdf"],
        body: "Good morning Grace,\n\nCheck-in is from 15:00, but I have marked your arrival as 13:00 and housekeeping is prioritising your room. If it is not ready we will store your luggage and you can use the courtyard lounge.\n\nWe have a covered garage under the hotel at €18 per night, height limit 1.90 m. Shall I reserve a space for two nights?",
        buttons: ["Reserve parking", "No thank you"],
      },
      {
        id: "m-5-3",
        author: "system",
        channel: "internal",
        at: "07:44",
        body: "Housekeeping task created — Room 401 priority clean before 13:00. Sent to Maria Silva on WhatsApp.",
      },
    ],
  },
  {
    id: "c-6",
    guest: guests.weiss,
    stage: "in-house",
    channels: ["whatsapp"],
    primaryChannel: "whatsapp",
    aiStatus: "resolved",
    sentiment: "positive",
    subject: "Two extra towels for 212",
    summary:
      "Guest asked for two extra towels. AI created a housekeeping task, Kadir confirmed delivery on WhatsApp at 09:02 and the guest was informed automatically. Closed without staff involvement.",
    suggestedReply: "",
    knowledgeUsed: ["Housekeeping Request Routing.txt"],
    upsellIdeas: [],
    taskIds: ["t-4"],
    unread: 0,
    lastAt: "09:03",
    aiHandledCount: 3,
    messages: [
      {
        id: "m-6-1",
        author: "guest",
        channel: "whatsapp",
        at: "08:52",
        body: "Guten Morgen, könnten wir zwei zusätzliche Handtücher bekommen? Zimmer 212.",
      },
      {
        id: "m-6-2",
        author: "ai",
        channel: "whatsapp",
        at: "08:52",
        confidence: 0.98,
        body: "Guten Morgen Herr Weiss. Selbstverständlich — ich habe die Reinigung informiert, die Handtücher kommen in den nächsten Minuten.",
      },
      {
        id: "m-6-3",
        author: "system",
        channel: "internal",
        at: "08:53",
        body: "Housekeeping task created — 2 extra towels, room 212. Sent to Kadir Yılmaz on WhatsApp.",
      },
      {
        id: "m-6-4",
        author: "system",
        channel: "internal",
        at: "09:02",
        body: "Kadir Yılmaz marked the task Completed via WhatsApp.",
      },
      {
        id: "m-6-5",
        author: "ai",
        channel: "whatsapp",
        at: "09:03",
        confidence: 0.99,
        body: "Ihre Handtücher wurden gebracht. Melden Sie sich gern, wenn Sie noch etwas brauchen.",
      },
    ],
  },
  {
    id: "c-7",
    guest: guests.tanabe,
    stage: "pre-arrival",
    channels: ["gmail"],
    primaryChannel: "gmail",
    aiStatus: "human-takeover",
    sentiment: "positive",
    subject: "VIP arrival 14:00 — preferences",
    summary:
      "Fifth stay. Asked for a high floor away from the lift, still water in the room and a dinner reservation for two at 20:00. Amélie took the conversation over to arrange the restaurant personally.",
    suggestedReply:
      "Mr Tanabe, room 307 is on the top floor at the courtyard end, away from the lift. I have booked De Kleine Zavel for 20:00 and there will be still water waiting for you.",
    knowledgeUsed: ["Local Recommendations — Restaurants.pdf", "VIP Handling.docx"],
    upsellIdeas: [
      { label: "Airport transfer on departure", value: "€68.00", reason: "Previous stays included transfer" },
    ],
    taskIds: ["t-5"],
    unread: 0,
    lastAt: "08:26",
    aiHandledCount: 2,
    messages: [
      {
        id: "m-7-1",
        author: "guest",
        channel: "gmail",
        at: "07:12",
        body: "Dear Mercier team,\n\nLooking forward to being back this afternoon, arriving about 14:00. If possible a high floor away from the lift, and could you recommend somewhere for dinner tonight around 20:00 for two?\n\nBest regards,\nYuki Tanabe",
      },
      {
        id: "m-7-2",
        author: "ai",
        channel: "gmail",
        at: "07:13",
        confidence: 0.9,
        knowledge: ["Local Recommendations — Restaurants.pdf"],
        body: "Dear Mr Tanabe,\n\nWelcome back. You are in 307 on the top floor, courtyard end — the quietest corner of that floor. For dinner I would suggest De Kleine Zavel, a ten minute walk, excellent seafood; or Bar Burbure for something more informal.\n\nI have asked a colleague to confirm the reservation personally.",
      },
      {
        id: "m-7-3",
        author: "staff",
        channel: "internal",
        at: "08:26",
        staffName: "Amélie Duprez",
        body: "Taking this one — I'll call De Kleine Zavel when they open at 11:00 and confirm the 20:00 table. Also arranging still water and the fruit plate for 307.",
      },
    ],
  },
  {
    id: "c-8",
    guest: guests.raghavan,
    stage: "pre-arrival",
    channels: ["whatsapp"],
    primaryChannel: "whatsapp",
    aiStatus: "ai-handling",
    sentiment: "neutral",
    subject: "Baby cot for 14:00 arrival",
    summary:
      "Family arriving 14:00 with a nine-month-old. Baby cot requested and confirmed free of charge; housekeeping task created for room 208.",
    suggestedReply: "The cot is set up in 208 already — anything else you would like waiting in the room?",
    knowledgeUsed: ["Hotel Policy — Children.pdf"],
    upsellIdeas: [{ label: "Early check-in from 13:00", value: "€30.00", reason: "Long flight with infant" }],
    taskIds: ["t-7"],
    unread: 0,
    lastAt: "08:11",
    aiHandledCount: 2,
    messages: [
      {
        id: "m-8-1",
        author: "guest",
        channel: "whatsapp",
        at: "08:09",
        body: "Hi, we arrive today at 14:00 with our nine month old. Do you have a cot available?",
      },
      {
        id: "m-8-2",
        author: "ai",
        channel: "whatsapp",
        at: "08:10",
        confidence: 0.97,
        knowledge: ["Hotel Policy — Children.pdf"],
        body: "Hello Priya. Yes — a cot is free of charge for children under two and I have asked housekeeping to set one up in room 208 before you arrive. Would you like a bottle warmer as well?",
        buttons: ["Yes please", "Not needed"],
      },
      {
        id: "m-8-3",
        author: "system",
        channel: "internal",
        at: "08:11",
        body: "Housekeeping task created — baby cot, room 208, before 14:00.",
      },
    ],
  },
  {
    id: "c-9",
    guest: guests.bakke,
    stage: "post-stay",
    channels: ["email"],
    primaryChannel: "email",
    aiStatus: "ai-handling",
    sentiment: "neutral",
    subject: "Charger left in room 115",
    summary:
      "Guest left a laptop charger in 115 on 12 Aug. Housekeeping lost property log shows a matching item; AI offered shipping at cost and is waiting for the address.",
    suggestedReply: "We have it. Send me the address and I will post it today — €12.50 tracked within Europe.",
    knowledgeUsed: ["Lost Property Procedure.pdf"],
    upsellIdeas: [],
    taskIds: ["t-8"],
    unread: 0,
    lastAt: "yesterday 18:32",
    aiHandledCount: 2,
    messages: [
      {
        id: "m-9-1",
        author: "guest",
        channel: "email",
        at: "yesterday 18:20",
        body: "Hi, I think I left a black laptop charger in room 115 when I checked out on the 12th. Any chance it was found?",
      },
      {
        id: "m-9-2",
        author: "ai",
        channel: "email",
        at: "yesterday 18:32",
        confidence: 0.91,
        knowledge: ["Lost Property Procedure.pdf"],
        body: "Hello Lars,\n\nGood news — our housekeeping log has a black 65W charger from 115, found on 12 August. We can post it to you tracked for €12.50, or hold it at reception for three months. Just send me the address you would like to use.",
      },
    ],
  },
  {
    id: "c-10",
    guest: guests.novak,
    stage: "in-house",
    channels: ["whatsapp"],
    primaryChannel: "whatsapp",
    aiStatus: "resolved",
    sentiment: "positive",
    subject: "Anniversary dinner + late breakfast",
    summary:
      "Anniversary couple in 310. AI recommended two restaurants, booked nothing directly, and sold a romantic package (€65) plus late breakfast in the room.",
    suggestedReply: "",
    knowledgeUsed: ["Local Recommendations — Restaurants.pdf", "Upsells — Packages.csv"],
    upsellIdeas: [],
    taskIds: [],
    unread: 0,
    lastAt: "07:58",
    aiHandledCount: 5,
    messages: [
      {
        id: "m-10-1",
        author: "guest",
        channel: "whatsapp",
        at: "07:50",
        body: "It's our anniversary tonight — anything you'd recommend? Also is breakfast still on at 10:15?",
      },
      {
        id: "m-10-2",
        author: "ai",
        channel: "whatsapp",
        at: "07:51",
        confidence: 0.96,
        knowledge: ["Hotel Policy — Breakfast.pdf", "Local Recommendations — Restaurants.pdf"],
        body: "Happy anniversary. Breakfast runs to 10:30, so 10:15 is fine.\n\nFor tonight: The Jane if you would like something special (book ahead), or Nathan for a warmer, smaller room. Both a short walk.\n\nWe also have a room package — champagne, chocolates and a late 12:00 checkout — for €65. Would you like it set up while you are out?",
        buttons: ["Yes, set it up", "Maybe later"],
      },
      { id: "m-10-3", author: "guest", channel: "whatsapp", at: "07:57", body: "Yes please, set it up!" },
      {
        id: "m-10-4",
        author: "ai",
        channel: "whatsapp",
        at: "07:58",
        confidence: 0.98,
        body: "Lovely — it will be in the room by 18:00 and €65 is added to your folio. Enjoy your evening.",
      },
    ],
  },
];

export const seedTasks: Task[] = [
  {
    id: "t-1",
    title: "Late checkout 15:00 — decision needed",
    detail: "Guest asked for 15:00. 24 arrivals today; 205 is needed for a 15:00 check-in.",
    room: "205",
    guest: "Hendrik Vos",
    department: "Front Office",
    priority: "Normal",
    createdAt: "09:19",
    due: "10:30",
    assignee: "Amélie Duprez",
    status: "New",
    source: "Guest WhatsApp",
    conversationId: "c-3",
    trail: [{ at: "09:19", text: "Created from guest WhatsApp by AI intent detection", via: "ai" }],
  },
  {
    id: "t-2",
    title: "Priority clean before 13:00 early arrival",
    detail: "Grace Okonkwo arriving 13:00, Deluxe King 401.",
    room: "401",
    guest: "Grace Okonkwo",
    department: "Housekeeping",
    priority: "High",
    createdAt: "07:44",
    due: "12:45",
    assignee: "Maria Silva",
    status: "Completed",
    source: "AI Detection",
    conversationId: "c-5",
    trail: [
      { at: "07:44", text: "Created from pre-arrival email — early arrival 13:00", via: "ai" },
      { at: "07:45", text: "Sent to Maria Silva on WhatsApp", via: "whatsapp" },
      { at: "11:48", text: "Maria Silva: Start Cleaning", via: "whatsapp" },
      { at: "12:26", text: "Maria Silva: Cleaned — room released", via: "whatsapp" },
    ],
  },
  {
    id: "t-3",
    title: "Air conditioning not cooling",
    detail: "Split unit runs but blows warm. Guest in house until 19 Aug.",
    room: "302",
    guest: "Clara Bertrand",
    department: "Maintenance",
    priority: "High",
    createdAt: "08:32",
    due: "11:00",
    assignee: "Peter Janssens",
    status: "In Progress",
    source: "Guest WhatsApp",
    conversationId: "c-1",
    trail: [
      { at: "08:32", text: "Created from guest WhatsApp — routed to Maintenance", via: "ai" },
      { at: "09:20", text: "Peter Janssens: Accept", via: "whatsapp" },
      { at: "09:35", text: "Peter Janssens: checking condenser on the roof", via: "whatsapp" },
    ],
  },
  {
    id: "t-4",
    title: "2 extra towels",
    room: "212",
    guest: "Daniel Weiss",
    department: "Housekeeping",
    priority: "Normal",
    createdAt: "08:53",
    assignee: "Kadir Yılmaz",
    status: "Completed",
    source: "Guest WhatsApp",
    conversationId: "c-6",
    trail: [
      { at: "08:53", text: "Created from guest WhatsApp", via: "ai" },
      { at: "09:02", text: "Kadir Yılmaz: Completed", via: "whatsapp" },
      { at: "09:03", text: "Guest informed automatically", via: "ai" },
    ],
  },
  {
    id: "t-5",
    title: "VIP preparation — 307",
    detail: "Still water, fruit plate, high floor away from lift. Confirm 20:00 table at De Kleine Zavel.",
    room: "307",
    guest: "Yuki Tanabe",
    department: "VIP",
    priority: "High",
    createdAt: "07:15",
    due: "13:30",
    assignee: "Amélie Duprez",
    status: "In Progress",
    source: "PMS event",
    conversationId: "c-7",
    trail: [
      { at: "07:15", text: "Created from PMS arrival list — VIP flag, 5th stay", via: "ai" },
      { at: "08:26", text: "Amélie Duprez took over the conversation", via: "dashboard" },
    ],
  },
  {
    id: "t-6",
    title: "Approve €47.60 credit note",
    detail: "Duplicate city tax €10.60 and minibar €26.40 posted to wrong room. Folio MRC-47988.",
    room: "411",
    guest: "Nadia Haddad",
    department: "Billing",
    priority: "High",
    createdAt: "08:05",
    due: "17:00",
    assignee: "Jonas Verhaeghe",
    status: "Escalated",
    source: "Guest Email",
    conversationId: "c-4",
    trail: [{ at: "08:05", text: "Auto-escalated — billing dispute rule", via: "ai" }],
  },
  {
    id: "t-7",
    title: "Baby cot in 208 before 14:00",
    room: "208",
    guest: "Priya Raghavan",
    department: "Housekeeping",
    priority: "Normal",
    createdAt: "08:11",
    due: "13:30",
    assignee: "Inês Duarte",
    status: "Assigned",
    source: "Guest WhatsApp",
    conversationId: "c-8",
    trail: [
      { at: "08:11", text: "Created from guest WhatsApp", via: "ai" },
      { at: "08:12", text: "Sent to Inês Duarte on WhatsApp", via: "whatsapp" },
    ],
  },
  {
    id: "t-8",
    title: "Post laptop charger to guest",
    detail: "Black 65W charger from 115, logged 12 Aug. Waiting for the address.",
    room: "115",
    guest: "Lars Bakke",
    department: "Follow-up",
    priority: "Low",
    createdAt: "yesterday 18:33",
    assignee: "Thibault Mertens",
    status: "Waiting",
    source: "Guest Email",
    conversationId: "c-9",
    trail: [{ at: "yesterday 18:33", text: "Created from post-stay email", via: "ai" }],
  },
  {
    id: "t-9",
    title: "Shower drain leaking into 207 ceiling",
    detail: "Reported by housekeeping during stayover clean.",
    room: "307",
    department: "Maintenance",
    priority: "Urgent",
    createdAt: "09:06",
    assignee: "Milan Novák",
    status: "In Progress",
    source: "Housekeeping",
    trail: [
      { at: "09:06", text: "Rosa Ferreira reported via WhatsApp", via: "whatsapp" },
      { at: "09:07", text: "Ticket MT-115 created, Front Office warned — arrival 14:00", via: "ai" },
      { at: "09:11", text: "Milan Novák: Accept", via: "whatsapp" },
    ],
  },
  {
    id: "t-10",
    title: "Taxi to Antwerpen-Centraal, 15:45",
    room: "212",
    guest: "Daniel Weiss",
    department: "Front Office",
    priority: "Normal",
    createdAt: "09:12",
    due: "15:30",
    status: "New",
    source: "Guest WhatsApp",
    trail: [{ at: "09:12", text: "Created from guest WhatsApp", via: "ai" }],
  },
  {
    id: "t-11",
    title: "Missing payment — card declined on 208",
    detail: "Pre-authorisation failed twice. Request new card at check-in.",
    room: "208",
    guest: "Priya Raghavan",
    department: "Front Office",
    priority: "High",
    createdAt: "06:40",
    due: "14:00",
    assignee: "Amélie Duprez",
    status: "Assigned",
    source: "PMS event",
    trail: [{ at: "06:40", text: "PMS webhook: authorisation failure", via: "ai" }],
  },
  {
    id: "t-12",
    title: "Room move request — 302 to 310",
    detail: "Pending manager decision on compensation vs upgrade.",
    room: "302",
    guest: "Clara Bertrand",
    department: "Front Office",
    priority: "High",
    createdAt: "09:53",
    assignee: "Jonas Verhaeghe",
    status: "Escalated",
    source: "AI Detection",
    conversationId: "c-1",
    trail: [{ at: "09:53", text: "Suggested by AI as an alternative to a rate reduction", via: "ai" }],
  },
];

export const seedRooms: Room[] = [
  { number: "115", floor: 1, status: "Clean", cleaningType: "Departure", guestStatus: "Vacant", priority: "Low", cleaner: "Alina Popescu", updatedAt: "08:40", vip: false },
  { number: "118", floor: 1, status: "Dirty", cleaningType: "Departure", guestStatus: "Checked out 09:05", priority: "Normal", cleaner: "Alina Popescu", updatedAt: "09:05", vip: false },
  { number: "121", floor: 1, status: "Inspected", cleaningType: "Departure", guestStatus: "Vacant", priority: "Low", cleaner: "Alina Popescu", updatedAt: "09:58", vip: false },
  { number: "201", floor: 2, status: "Cleaning", cleaningType: "Departure", guestStatus: "Checked out 08:12", arrivalTime: "16:00", priority: "Normal", cleaner: "Maria Silva", updatedAt: "09:44", vip: false },
  { number: "205", floor: 2, status: "Guest Inside", cleaningType: "Stayover", guestStatus: "Late checkout pending", priority: "Normal", cleaner: "Maria Silva", updatedAt: "09:21", vip: false, note: "Awaiting late checkout decision" },
  { number: "207", floor: 2, status: "Maintenance", cleaningType: "Departure", guestStatus: "Vacant", arrivalTime: "15:00", priority: "High", cleaner: "Maria Silva", updatedAt: "09:07", vip: false, note: "Ceiling stain — leak from 307" },
  { number: "208", floor: 2, status: "Dirty", cleaningType: "Departure", guestStatus: "Vacant", arrivalTime: "14:00", priority: "High", cleaner: "Inês Duarte", updatedAt: "08:50", vip: false, note: "Baby cot required" },
  { number: "212", floor: 2, status: "Clean", cleaningType: "Stayover", guestStatus: "In house", priority: "Normal", cleaner: "Kadir Yılmaz", updatedAt: "09:02", vip: false },
  { number: "216", floor: 2, status: "DND", cleaningType: "Stayover", guestStatus: "Do not disturb since 08:30", priority: "Low", cleaner: "Kadir Yılmaz", updatedAt: "08:34", vip: false },
  { number: "302", floor: 3, status: "Guest Inside", cleaningType: "Stayover + Linen", guestStatus: "In house — unhappy", priority: "High", cleaner: "Inês Duarte", updatedAt: "09:52", vip: false, note: "AC issue open, guest may move to 310" },
  { number: "307", floor: 3, status: "Maintenance", cleaningType: "VIP Arrival", guestStatus: "Vacant", arrivalTime: "14:00", priority: "Urgent", cleaner: "Inês Duarte", updatedAt: "09:11", vip: true, note: "Shower leak — VIP arrival at 14:00" },
  { number: "310", floor: 3, status: "Cleaning", cleaningType: "Stayover", guestStatus: "In house", priority: "Normal", cleaner: "Inês Duarte", updatedAt: "09:36", vip: false, note: "Anniversary package to be set up by 18:00" },
  { number: "312", floor: 3, status: "Dirty", cleaningType: "Stayover + Linen", guestStatus: "In house", priority: "Normal", cleaner: "Kadir Yılmaz", updatedAt: "07:30", vip: false },
  { number: "318", floor: 3, status: "Blocked", cleaningType: "Deep Clean", guestStatus: "Out of service", priority: "Low", updatedAt: "yesterday 16:20", vip: false, note: "Repainting — back in service 20 Aug" },
  { number: "401", floor: 4, status: "Inspected", cleaningType: "Departure", guestStatus: "Vacant", arrivalTime: "13:00", priority: "High", cleaner: "Maria Silva", updatedAt: "12:26", vip: false, note: "Early arrival 13:00 — released" },
  { number: "405", floor: 4, status: "Dirty", cleaningType: "Departure", guestStatus: "Checked out 09:40", arrivalTime: "17:30", priority: "Normal", cleaner: "Maria Silva", updatedAt: "09:40", vip: false },
  { number: "409", floor: 4, status: "Clean", cleaningType: "Stayover", guestStatus: "In house", priority: "Low", cleaner: "Alina Popescu", updatedAt: "09:12", vip: false },
  { number: "411", floor: 4, status: "Dirty", cleaningType: "Departure", guestStatus: "Vacant", priority: "Normal", cleaner: "Alina Popescu", updatedAt: "08:05", vip: false, note: "Minibar audit requested — billing dispute" },
];

export const seedIssues: Issue[] = [
  {
    id: "MT-114",
    room: "302",
    title: "Air conditioning not cooling",
    detail: "Split unit runs, fan fine, air stays warm. Suspect condenser fan or low refrigerant.",
    priority: "High",
    reportedBy: "Clara Bertrand",
    via: "Guest via WhatsApp",
    createdAt: "08:32",
    assignee: "Peter Janssens",
    status: "In Progress",
    outOfService: false,
    updates: [
      { at: "09:20", text: "Accepted on WhatsApp", via: "whatsapp" },
      { at: "09:35", text: "Roof condenser fan not spinning — checking capacitor", via: "whatsapp" },
    ],
  },
  {
    id: "MT-115",
    room: "307",
    title: "Shower drain leaking into 207 ceiling",
    detail: "Water tracking through the slab into 207. Seal or waste trap failure.",
    priority: "Urgent",
    reportedBy: "Rosa Ferreira",
    via: "Housekeeping via WhatsApp",
    createdAt: "09:06",
    assignee: "Milan Novák",
    status: "In Progress",
    outOfService: true,
    updates: [
      { at: "09:07", text: "Front Office warned — VIP arrival 14:00 for this room", via: "dashboard" },
      { at: "09:11", text: "Accepted on WhatsApp", via: "whatsapp" },
      { at: "09:48", text: "Waste trap cracked. Replacement in the van, 30 min", via: "whatsapp" },
    ],
  },
  {
    id: "MT-116",
    room: "118",
    title: "Bathroom light flickering",
    detail: "LED driver buzzing when dimmed.",
    priority: "Normal",
    reportedBy: "Alina Popescu",
    via: "Housekeeping via WhatsApp",
    createdAt: "09:05",
    status: "Open",
    outOfService: false,
    updates: [{ at: "09:05", text: "Reported during departure clean", via: "whatsapp" }],
  },
  {
    id: "MT-117",
    room: "Lobby",
    title: "Automatic door sensor mistriggering",
    detail: "Door opens with no one present, roughly every ten minutes.",
    priority: "Normal",
    reportedBy: "Amélie Duprez",
    via: "Front Office",
    createdAt: "08:18",
    assignee: "Peter Janssens",
    status: "Waiting Parts",
    outOfService: false,
    updates: [{ at: "08:44", text: "Sensor ordered, arrives Wednesday. Reduced range in the meantime", via: "dashboard" }],
  },
  {
    id: "MT-118",
    room: "318",
    title: "Repainting after water damage",
    detail: "Planned works, room blocked in PMS until 20 Aug.",
    priority: "Low",
    reportedBy: "Jonas Verhaeghe",
    via: "AI Detection",
    createdAt: "yesterday 16:20",
    assignee: "Milan Novák",
    status: "In Progress",
    outOfService: true,
    updates: [{ at: "yesterday 16:22", text: "Room blocked in PMS until 20 Aug", via: "dashboard" }],
  },
  {
    id: "MT-113",
    room: "409",
    title: "Safe not closing",
    detail: "Battery replaced, latch realigned.",
    priority: "Normal",
    reportedBy: "Hendrik Vos",
    via: "Guest via WhatsApp",
    createdAt: "07:22",
    assignee: "Peter Janssens",
    status: "Completed",
    outOfService: false,
    updates: [{ at: "08:02", text: "Completed on WhatsApp — guest informed automatically", via: "whatsapp" }],
  },
];

export const seedUpsells: Upsell[] = [
  { id: "up-1", guest: "Elena Novak", room: "310", offer: "Romantic package (champagne, chocolates, 12:00 checkout)", value: 65, channel: "whatsapp", status: "Accepted", date: "Today 07:58" },
  { id: "up-2", guest: "Daniel Weiss", room: "212", offer: "Breakfast, 2 mornings", value: 26, channel: "whatsapp", status: "Accepted", date: "Today 08:14" },
  { id: "up-3", guest: "Grace Okonkwo", room: "401", offer: "Garage parking, 2 nights", value: 36, channel: "outlook", status: "Accepted", date: "Today 07:41" },
  { id: "up-4", guest: "Sofia Marchetti", offer: "Breakfast for 2, both mornings", value: 52, channel: "whatsapp", status: "Sent", date: "Today 09:47" },
  { id: "up-5", guest: "Sofia Marchetti", offer: "Private airport transfer", value: 68, channel: "whatsapp", status: "Sent", date: "Today 09:47" },
  { id: "up-6", guest: "Hendrik Vos", room: "205", offer: "Late checkout until 14:00", value: 35, channel: "whatsapp", status: "Sent", date: "Today 09:19" },
  { id: "up-7", guest: "Priya Raghavan", room: "208", offer: "Early check-in from 13:00", value: 30, channel: "whatsapp", status: "Sent", date: "Today 08:10" },
  { id: "up-8", guest: "Yuki Tanabe", room: "307", offer: "Airport transfer on departure", value: 68, channel: "gmail", status: "Sent", date: "Today 07:13" },
  { id: "up-9", guest: "Marta Cieślak", room: "121", offer: "Room upgrade to Junior Suite", value: 79, channel: "whatsapp", status: "Accepted", date: "Today 06:52" },
  { id: "up-10", guest: "Tomás Ferreira", room: "409", offer: "Bicycle rental, 2 days", value: 24, channel: "whatsapp", status: "Accepted", date: "Today 08:36" },
  { id: "up-11", guest: "Anke Willems", room: "118", offer: "Late checkout until 14:00", value: 35, channel: "email", status: "Declined", date: "Today 07:20" },
  { id: "up-12", guest: "Ruben Claes", offer: "Restaurant reservation — De Kleine Zavel", value: 0, channel: "whatsapp", status: "Accepted", date: "Today 09:02" },
  { id: "up-13", guest: "Ingrid Sørensen", room: "405", offer: "Extra bed", value: 45, channel: "gmail", status: "Expired", date: "Yesterday 19:04" },
  { id: "up-14", guest: "Marta Cieślak", room: "121", offer: "Breakfast, 1 morning", value: 13, channel: "whatsapp", status: "Accepted", date: "Today 06:53" },
];

export const knowledgeDocs: KnowledgeDoc[] = [
  { id: "k-1", name: "Hotel Policy — Check-in & Check-out.pdf", category: "Hotel Policies", format: "PDF", size: "241 KB", updated: "4 Aug", status: "Indexed", aiReady: true, usedToday: 31 },
  { id: "k-2", name: "Hotel Policy — Breakfast.pdf", category: "Hotel Policies", format: "PDF", size: "118 KB", updated: "2 Jul", status: "Indexed", aiReady: true, usedToday: 46 },
  { id: "k-3", name: "Hotel Policy — Pets, Smoking & Noise.pdf", category: "Hotel Policies", format: "PDF", size: "96 KB", updated: "19 Jun", status: "Indexed", aiReady: true, usedToday: 7 },
  { id: "k-4", name: "Cancellation & Deposit Terms.docx", category: "Hotel Policies", format: "DOCX", size: "64 KB", updated: "11 Aug", status: "Indexed", aiReady: true, usedToday: 4 },
  { id: "k-5", name: "Billing & Refund Policy.pdf", category: "Hotel Policies", format: "PDF", size: "152 KB", updated: "11 Aug", status: "Needs Review", aiReady: false, usedToday: 2 },
  { id: "k-6", name: "Hotel Information — Wi-Fi, Parking, Facilities.pdf", category: "Hotel Information", format: "PDF", size: "318 KB", updated: "9 Aug", status: "Indexed", aiReady: true, usedToday: 58 },
  { id: "k-7", name: "Room Categories & Descriptions.pdf", category: "Hotel Information", format: "PDF", size: "1.2 MB", updated: "28 Jul", status: "Indexed", aiReady: true, usedToday: 22 },
  { id: "k-8", name: "Emergency Procedures.docx", category: "Hotel Information", format: "DOCX", size: "87 KB", updated: "3 Mar", status: "Indexed", aiReady: true, usedToday: 0 },
  { id: "k-9", name: "Local Recommendations — Restaurants & Bars.pdf", category: "Local Recommendations", format: "PDF", size: "486 KB", updated: "14 Aug", status: "Indexed", aiReady: true, usedToday: 19 },
  { id: "k-10", name: "Local Recommendations — Museums & Walks.txt", category: "Local Recommendations", format: "TXT", size: "22 KB", updated: "14 Aug", status: "Indexed", aiReady: true, usedToday: 6 },
  { id: "k-11", name: "Pharmacies, Supermarkets & Transport.txt", category: "Local Recommendations", format: "TXT", size: "18 KB", updated: "1 Aug", status: "Indexed", aiReady: true, usedToday: 3 },
  { id: "k-12", name: "Upsell Catalogue & Prices.csv", category: "Upsells", format: "CSV", size: "9 KB", updated: "17 Aug", status: "Indexed", aiReady: true, usedToday: 27 },
  { id: "k-13", name: "Transfer & Experience Partners.csv", category: "Upsells", format: "CSV", size: "6 KB", updated: "17 Aug", status: "Processing", aiReady: false, usedToday: 0 },
];

export const planTiers: PlanTier[] = [
  {
    key: "starter",
    name: "Starter",
    pricePerRoom: 4,
    blurb: "One channel, the knowledge base and the AI inbox. For small properties testing the water.",
    features: [
      "WhatsApp or email — one channel",
      "AI answers from your knowledge base",
      "Up to 25 knowledge sources",
      "Guest request tasks",
      "Email support",
    ],
    seats: 5,
    knowledgeDocs: 25,
  },
  {
    key: "professional",
    name: "Professional",
    pricePerRoom: 7,
    blurb: "Every channel, the PMS connection and the full operations layer on WhatsApp.",
    features: [
      "WhatsApp and email together",
      "PMS connection — availability, rates, folios",
      "Housekeeping and maintenance on WhatsApp",
      "Upsell engine and revenue reporting",
      "Unlimited knowledge sources",
      "Priority support",
    ],
    seats: 25,
    knowledgeDocs: null,
  },
  {
    key: "enterprise",
    name: "Enterprise",
    pricePerRoom: 11,
    blurb: "Multi-property, custom integrations and a named account manager.",
    features: [
      "Everything in Professional",
      "Multiple properties on one account",
      "Custom PMS and POS integrations",
      "Single sign-on and audit export",
      "Named account manager",
      "99.9% uptime commitment",
    ],
    seats: null,
    knowledgeDocs: null,
  },
];

export const subscription: Subscription = {
  plan: "professional",
  status: "Active",
  billingCycle: "monthly",
  rooms: 48,
  startedOn: "14 Feb 2026",
  renewsOn: "14 Sep 2026",
  seatsUsed: 6,
  paymentMethod: { brand: "Visa", last4: "4417", expiry: "09/28", holder: "Hotel Mercier BV" },
  usage: { conversations: 1284, aiReplies: 1121, whatsappMessages: 4392, upsellRevenue: 8412.5 },
};

export const invoices: Invoice[] = [
  { id: "inv-8", number: "HGX-2026-0208", date: "14 Aug 2026", period: "14 Aug — 13 Sep 2026", amount: 336, status: "Open" },
  { id: "inv-7", number: "HGX-2026-0181", date: "14 Jul 2026", period: "14 Jul — 13 Aug 2026", amount: 336, status: "Paid" },
  { id: "inv-6", number: "HGX-2026-0154", date: "14 Jun 2026", period: "14 Jun — 13 Jul 2026", amount: 336, status: "Paid" },
  { id: "inv-5", number: "HGX-2026-0129", date: "14 May 2026", period: "14 May — 13 Jun 2026", amount: 336, status: "Paid" },
  { id: "inv-4", number: "HGX-2026-0103", date: "14 Apr 2026", period: "14 Apr — 13 May 2026", amount: 336, status: "Paid" },
  { id: "inv-3", number: "HGX-2026-0077", date: "14 Mar 2026", period: "14 Mar — 13 Apr 2026", amount: 192, status: "Paid" },
  { id: "inv-2", number: "HGX-2026-0051", date: "14 Feb 2026", period: "14 Feb — 13 Mar 2026", amount: 0, status: "Paid" },
];

export const aiRules: AiRule[] = [
  { topic: "General questions", mode: "Autonomous", note: "Wi-Fi, directions, opening hours" },
  { topic: "Hotel information", mode: "Autonomous", note: "Answered from the knowledge base" },
  { topic: "Availability & pricing", mode: "Autonomous", note: "Reads Mews, never books" },
  { topic: "Upsells", mode: "Autonomous", note: "Only offers from the priced catalogue" },
  { topic: "Housekeeping requests", mode: "Autonomous", note: "Creates tasks and confirms to the guest" },
  { topic: "Maintenance reports", mode: "Autonomous", note: "Opens a ticket, notifies the technician" },
  { topic: "Late checkout / early check-in", mode: "Human Approval", note: "Depends on occupancy" },
  { topic: "Complaints", mode: "Human Approval", note: "AI drafts, a human sends" },
  { topic: "Refunds", mode: "Always Escalate", note: "Never handled by AI" },
  { topic: "Billing disputes", mode: "Always Escalate", note: "Folio pulled and attached" },
  { topic: "Safety issues", mode: "Always Escalate", note: "Duty manager notified immediately" },
  { topic: "VIP guests", mode: "Human Approval", note: "AI prepares, staff confirms" },
];

export const seedActivity: ActivityItem[] = [
  { id: "a-1", at: "09:52", kind: "escalation", text: "Escalated 302 — compensation requested by Clara Bertrand", meta: "WhatsApp" },
  { id: "a-2", at: "09:47", kind: "upsell", text: "Offered breakfast and airport transfer to Sofia Marchetti", meta: "€120.00 proposed" },
  { id: "a-3", at: "09:44", kind: "room", text: "Maria Silva started cleaning 201", meta: "WhatsApp" },
  { id: "a-4", at: "09:39", kind: "ai-reply", text: "Checked live availability for 22–24 Aug and recommended the Deluxe King", meta: "Mews" },
  { id: "a-5", at: "09:21", kind: "task", text: "Late checkout decision for 205 sent to Front Office", meta: "Task t-1" },
  { id: "a-6", at: "09:12", kind: "task", text: "Taxi booked for 212 at 15:45", meta: "WhatsApp" },
  { id: "a-7", at: "09:11", kind: "maintenance", text: "Milan Novák accepted the 307 shower leak", meta: "MT-115" },
  { id: "a-8", at: "09:03", kind: "guest", text: "Confirmed towel delivery to 212 in German", meta: "WhatsApp" },
  { id: "a-9", at: "08:44", kind: "ai-reply", text: "Answered a parking question for tomorrow's arrival", meta: "Gmail" },
  { id: "a-10", at: "08:36", kind: "upsell", text: "Sold two days of bicycle rental to 409", meta: "€24.00" },
  { id: "a-11", at: "08:14", kind: "upsell", text: "Added breakfast for 212, two mornings", meta: "€26.00" },
  { id: "a-12", at: "08:05", kind: "escalation", text: "Billing dispute from Nadia Haddad escalated to the manager", meta: "Gmail" },
  { id: "a-13", at: "07:58", kind: "upsell", text: "Sold the romantic package to 310", meta: "€65.00" },
  { id: "a-14", at: "07:41", kind: "ai-reply", text: "Sent parking and early arrival information to Grace Okonkwo", meta: "Outlook" },
];

export const seedWaThreads: WaThread[] = [
  {
    id: "wa-maria",
    contact: "Maria Silva",
    role: "Room Attendant · Floors 2 & 4",
    phone: "+32 468 22 74 91",
    department: "Housekeeping",
    messages: [
      {
        id: "wa-m1",
        from: "hotelogx",
        at: "07:02",
        body: "Good morning Maria.\n\nYour rooms today:\n\n401 — Departure · Early arrival 13:00\n405 — Departure\n201 — Departure · Arrival 16:00\n205 — Stayover\n\nSelect a room to start.",
        buttons: [{ label: "401" }, { label: "405" }, { label: "201" }, { label: "205" }],
        chosen: "401",
      },
      {
        id: "wa-m2",
        from: "hotelogx",
        at: "11:47",
        body: "Room 401 — Departure\nEarly arrival at 13:00, please prioritise.\n\nChoose status:",
        buttons: [{ label: "Start Cleaning" }, { label: "Guest Inside" }, { label: "DND" }, { label: "Maintenance Issue" }],
        chosen: "Start Cleaning",
      },
      {
        id: "wa-m3",
        from: "hotelogx",
        at: "12:26",
        body: "Room 401 — cleaning in progress since 11:48.",
        buttons: [{ label: "Cleaned" }, { label: "Needs Inspection" }, { label: "Maintenance Issue" }],
        chosen: "Cleaned",
      },
      {
        id: "wa-m4",
        from: "hotelogx",
        at: "12:27",
        body: "Thank you. 401 is released and reception has been told it is ready for the 13:00 arrival.\n\nNext room: 405 — Departure, arrival 17:30.",
        buttons: [{ label: "Start Cleaning" }, { label: "Guest Inside" }, { label: "DND" }, { label: "Maintenance Issue" }],
      },
      {
        id: "wa-m5",
        from: "hotelogx",
        at: "09:44",
        body: "Room 201 — cleaning in progress.\n\nWhen you are done:",
        buttons: [{ label: "Cleaned" }, { label: "Needs Inspection" }, { label: "Maintenance Issue" }],
      },
    ],
  },
  {
    id: "wa-ines",
    contact: "Inês Duarte",
    role: "Room Attendant · Floor 3",
    phone: "+32 468 22 74 88",
    department: "Housekeeping",
    messages: [
      {
        id: "wa-i1",
        from: "hotelogx",
        at: "07:02",
        body: "Good morning Inês.\n\nYour rooms today:\n\n307 — VIP arrival 14:00\n302 — Stayover + linen change\n310 — Stayover\n208 — Departure · Arrival 14:00, baby cot\n\nSelect a room to start.",
        buttons: [{ label: "307" }, { label: "302" }, { label: "310" }, { label: "208" }],
        chosen: "310",
      },
      {
        id: "wa-i2",
        from: "hotelogx",
        at: "09:36",
        body: "Room 310 — Stayover\nAnniversary package to be set up by 18:00.\n\nChoose status:",
        buttons: [{ label: "Start Cleaning" }, { label: "Guest Inside" }, { label: "DND" }, { label: "Maintenance Issue" }],
        chosen: "Start Cleaning",
      },
      {
        id: "wa-i3",
        from: "hotelogx",
        at: "09:37",
        body: "Room 310 — cleaning in progress.\n\nWhen you are done:",
        buttons: [{ label: "Cleaned" }, { label: "Needs Inspection" }, { label: "Maintenance Issue" }],
      },
      {
        id: "wa-i4",
        from: "hotelogx",
        at: "09:40",
        body: "Room 208 — Departure\nArrival at 14:00, baby cot required.\n\nChoose status:",
        buttons: [{ label: "Start Cleaning" }, { label: "Guest Inside" }, { label: "DND" }, { label: "Maintenance Issue" }],
      },
    ],
  },
  {
    id: "wa-peter",
    contact: "Peter Janssens",
    role: "Technical Manager",
    phone: "+32 494 31 62 18",
    department: "Maintenance",
    messages: [
      {
        id: "wa-p1",
        from: "hotelogx",
        at: "08:33",
        body: "New Maintenance Request\n\nRoom: 302\nIssue: Air conditioning not cooling\nPriority: High\nReported by: Guest via WhatsApp",
        buttons: [{ label: "Accept" }, { label: "Unable to Handle" }],
        chosen: "Accept",
      },
      {
        id: "wa-p2",
        from: "hotelogx",
        at: "09:20",
        body: "Thank you. MT-114 is assigned to you and the guest has been told a technician is on the way.\n\nRoom 302 — when you have finished:",
        buttons: [{ label: "Completed" }, { label: "Parts Required" }, { label: "External Technician Required" }],
      },
      {
        id: "wa-p3",
        from: "hotelogx",
        at: "08:19",
        body: "New Maintenance Request\n\nRoom: 118\nIssue: Bathroom light flickering\nPriority: Normal\nReported by: Housekeeping via WhatsApp",
        buttons: [{ label: "Accept" }, { label: "Unable to Handle" }],
      },
    ],
  },
  {
    id: "wa-milan",
    contact: "Milan Novák",
    role: "Technician",
    phone: "+32 494 31 62 44",
    department: "Maintenance",
    messages: [
      {
        id: "wa-n1",
        from: "hotelogx",
        at: "09:07",
        body: "New Maintenance Request\n\nRoom: 307\nIssue: Shower drain leaking into 207 ceiling\nPriority: Urgent\nReported by: Housekeeping via WhatsApp\n\nNote: VIP arrival for this room at 14:00.",
        buttons: [{ label: "Accept" }, { label: "Unable to Handle" }],
        chosen: "Accept",
      },
      {
        id: "wa-n2",
        from: "hotelogx",
        at: "09:11",
        body: "Room 307 — MT-115 assigned. Front Office has been warned about the 14:00 arrival.\n\nWhen you have finished:",
        buttons: [{ label: "Completed" }, { label: "Parts Required" }, { label: "External Technician Required" }],
      },
    ],
  },
];

export const dailyStats = {
  arrivals: 24,
  departures: 18,
  inHouse: 37,
  occupancy: "84%",
  vipArrivals: 2,
  earlyCheckIns: 3,
  guestRequests: 9,
  conversationsToday: 63,
  aiResolutionRate: 87.3,
  avgResponse: "38 sec",
  whatsappMessages: 214,
  emailMessages: 41,
  upsellToday: 284.5,
  upsellWeek: 2148.75,
  offersSent: 21,
  offersAccepted: 7,
  roomsPending: 4,
};

export const conversationTrend = [42, 51, 47, 58, 63, 71, 63];
export const aiTrend = [79, 82, 81, 85, 84, 88, 87];
export const upsellTrend = [186, 240, 312, 205, 388, 332, 284.5];
export const weekdays = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"];
