/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ManagerIndexRouteImport } from './routes/manager.index'
import { Route as MaintenanceIndexRouteImport } from './routes/maintenance.index'
import { Route as HousekeepingIndexRouteImport } from './routes/housekeeping.index'
import { Route as FrontOfficeIndexRouteImport } from './routes/front-office.index'
import { Route as ManagerUpsellsRouteImport } from './routes/manager.upsells'
import { Route as ManagerTasksRouteImport } from './routes/manager.tasks'
import { Route as ManagerSettingsRouteImport } from './routes/manager.settings'
import { Route as ManagerConversationsRouteImport } from './routes/manager.conversations'
import { Route as MaintenanceTasksRouteImport } from './routes/maintenance.tasks'
import { Route as MaintenanceIssuesRouteImport } from './routes/maintenance.issues'
import { Route as HousekeepingTasksRouteImport } from './routes/housekeeping.tasks'
import { Route as HousekeepingRoomsRouteImport } from './routes/housekeeping.rooms'
import { Route as FrontOfficeTasksRouteImport } from './routes/front-office.tasks'
import { Route as FrontOfficeConversationsRouteImport } from './routes/front-office.conversations'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerIndexRoute = ManagerIndexRouteImport.update({
  id: '/manager/',
  path: '/manager/',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceIndexRoute = MaintenanceIndexRouteImport.update({
  id: '/maintenance/',
  path: '/maintenance/',
  getParentRoute: () => rootRouteImport,
} as any)
const HousekeepingIndexRoute = HousekeepingIndexRouteImport.update({
  id: '/housekeeping/',
  path: '/housekeeping/',
  getParentRoute: () => rootRouteImport,
} as any)
const FrontOfficeIndexRoute = FrontOfficeIndexRouteImport.update({
  id: '/front-office/',
  path: '/front-office/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerUpsellsRoute = ManagerUpsellsRouteImport.update({
  id: '/manager/upsells',
  path: '/manager/upsells',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerTasksRoute = ManagerTasksRouteImport.update({
  id: '/manager/tasks',
  path: '/manager/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerSettingsRoute = ManagerSettingsRouteImport.update({
  id: '/manager/settings',
  path: '/manager/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerConversationsRoute = ManagerConversationsRouteImport.update({
  id: '/manager/conversations',
  path: '/manager/conversations',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceTasksRoute = MaintenanceTasksRouteImport.update({
  id: '/maintenance/tasks',
  path: '/maintenance/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceIssuesRoute = MaintenanceIssuesRouteImport.update({
  id: '/maintenance/issues',
  path: '/maintenance/issues',
  getParentRoute: () => rootRouteImport,
} as any)
const HousekeepingTasksRoute = HousekeepingTasksRouteImport.update({
  id: '/housekeeping/tasks',
  path: '/housekeeping/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const HousekeepingRoomsRoute = HousekeepingRoomsRouteImport.update({
  id: '/housekeeping/rooms',
  path: '/housekeeping/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const FrontOfficeTasksRoute = FrontOfficeTasksRouteImport.update({
  id: '/front-office/tasks',
  path: '/front-office/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const FrontOfficeConversationsRoute =
  FrontOfficeConversationsRouteImport.update({
    id: '/front-office/conversations',
    path: '/front-office/conversations',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/front-office/conversations': typeof FrontOfficeConversationsRoute
  '/front-office/tasks': typeof FrontOfficeTasksRoute
  '/housekeeping/rooms': typeof HousekeepingRoomsRoute
  '/housekeeping/tasks': typeof HousekeepingTasksRoute
  '/maintenance/issues': typeof MaintenanceIssuesRoute
  '/maintenance/tasks': typeof MaintenanceTasksRoute
  '/manager/conversations': typeof ManagerConversationsRoute
  '/manager/settings': typeof ManagerSettingsRoute
  '/manager/tasks': typeof ManagerTasksRoute
  '/manager/upsells': typeof ManagerUpsellsRoute
  '/front-office/': typeof FrontOfficeIndexRoute
  '/housekeeping/': typeof HousekeepingIndexRoute
  '/maintenance/': typeof MaintenanceIndexRoute
  '/manager/': typeof ManagerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/front-office/conversations': typeof FrontOfficeConversationsRoute
  '/front-office/tasks': typeof FrontOfficeTasksRoute
  '/housekeeping/rooms': typeof HousekeepingRoomsRoute
  '/housekeeping/tasks': typeof HousekeepingTasksRoute
  '/maintenance/issues': typeof MaintenanceIssuesRoute
  '/maintenance/tasks': typeof MaintenanceTasksRoute
  '/manager/conversations': typeof ManagerConversationsRoute
  '/manager/settings': typeof ManagerSettingsRoute
  '/manager/tasks': typeof ManagerTasksRoute
  '/manager/upsells': typeof ManagerUpsellsRoute
  '/front-office': typeof FrontOfficeIndexRoute
  '/housekeeping': typeof HousekeepingIndexRoute
  '/maintenance': typeof MaintenanceIndexRoute
  '/manager': typeof ManagerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/front-office/conversations': typeof FrontOfficeConversationsRoute
  '/front-office/tasks': typeof FrontOfficeTasksRoute
  '/housekeeping/rooms': typeof HousekeepingRoomsRoute
  '/housekeeping/tasks': typeof HousekeepingTasksRoute
  '/maintenance/issues': typeof MaintenanceIssuesRoute
  '/maintenance/tasks': typeof MaintenanceTasksRoute
  '/manager/conversations': typeof ManagerConversationsRoute
  '/manager/settings': typeof ManagerSettingsRoute
  '/manager/tasks': typeof ManagerTasksRoute
  '/manager/upsells': typeof ManagerUpsellsRoute
  '/front-office/': typeof FrontOfficeIndexRoute
  '/housekeeping/': typeof HousekeepingIndexRoute
  '/maintenance/': typeof MaintenanceIndexRoute
  '/manager/': typeof ManagerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/front-office/conversations'
    | '/front-office/tasks'
    | '/housekeeping/rooms'
    | '/housekeeping/tasks'
    | '/maintenance/issues'
    | '/maintenance/tasks'
    | '/manager/conversations'
    | '/manager/settings'
    | '/manager/tasks'
    | '/manager/upsells'
    | '/front-office/'
    | '/housekeeping/'
    | '/maintenance/'
    | '/manager/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/front-office/conversations'
    | '/front-office/tasks'
    | '/housekeeping/rooms'
    | '/housekeeping/tasks'
    | '/maintenance/issues'
    | '/maintenance/tasks'
    | '/manager/conversations'
    | '/manager/settings'
    | '/manager/tasks'
    | '/manager/upsells'
    | '/front-office'
    | '/housekeeping'
    | '/maintenance'
    | '/manager'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/onboarding'
    | '/front-office/conversations'
    | '/front-office/tasks'
    | '/housekeeping/rooms'
    | '/housekeeping/tasks'
    | '/maintenance/issues'
    | '/maintenance/tasks'
    | '/manager/conversations'
    | '/manager/settings'
    | '/manager/tasks'
    | '/manager/upsells'
    | '/front-office/'
    | '/housekeeping/'
    | '/maintenance/'
    | '/manager/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  FrontOfficeConversationsRoute: typeof FrontOfficeConversationsRoute
  FrontOfficeTasksRoute: typeof FrontOfficeTasksRoute
  HousekeepingRoomsRoute: typeof HousekeepingRoomsRoute
  HousekeepingTasksRoute: typeof HousekeepingTasksRoute
  MaintenanceIssuesRoute: typeof MaintenanceIssuesRoute
  MaintenanceTasksRoute: typeof MaintenanceTasksRoute
  ManagerConversationsRoute: typeof ManagerConversationsRoute
  ManagerSettingsRoute: typeof ManagerSettingsRoute
  ManagerTasksRoute: typeof ManagerTasksRoute
  ManagerUpsellsRoute: typeof ManagerUpsellsRoute
  FrontOfficeIndexRoute: typeof FrontOfficeIndexRoute
  HousekeepingIndexRoute: typeof HousekeepingIndexRoute
  MaintenanceIndexRoute: typeof MaintenanceIndexRoute
  ManagerIndexRoute: typeof ManagerIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/': {
      id: '/manager/'
      path: '/manager'
      fullPath: '/manager/'
      preLoaderRoute: typeof ManagerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance/': {
      id: '/maintenance/'
      path: '/maintenance'
      fullPath: '/maintenance/'
      preLoaderRoute: typeof MaintenanceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/housekeeping/': {
      id: '/housekeeping/'
      path: '/housekeeping'
      fullPath: '/housekeeping/'
      preLoaderRoute: typeof HousekeepingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/front-office/': {
      id: '/front-office/'
      path: '/front-office'
      fullPath: '/front-office/'
      preLoaderRoute: typeof FrontOfficeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/upsells': {
      id: '/manager/upsells'
      path: '/manager/upsells'
      fullPath: '/manager/upsells'
      preLoaderRoute: typeof ManagerUpsellsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/tasks': {
      id: '/manager/tasks'
      path: '/manager/tasks'
      fullPath: '/manager/tasks'
      preLoaderRoute: typeof ManagerTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/settings': {
      id: '/manager/settings'
      path: '/manager/settings'
      fullPath: '/manager/settings'
      preLoaderRoute: typeof ManagerSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/conversations': {
      id: '/manager/conversations'
      path: '/manager/conversations'
      fullPath: '/manager/conversations'
      preLoaderRoute: typeof ManagerConversationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance/tasks': {
      id: '/maintenance/tasks'
      path: '/maintenance/tasks'
      fullPath: '/maintenance/tasks'
      preLoaderRoute: typeof MaintenanceTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance/issues': {
      id: '/maintenance/issues'
      path: '/maintenance/issues'
      fullPath: '/maintenance/issues'
      preLoaderRoute: typeof MaintenanceIssuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/housekeeping/tasks': {
      id: '/housekeeping/tasks'
      path: '/housekeeping/tasks'
      fullPath: '/housekeeping/tasks'
      preLoaderRoute: typeof HousekeepingTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/housekeeping/rooms': {
      id: '/housekeeping/rooms'
      path: '/housekeeping/rooms'
      fullPath: '/housekeeping/rooms'
      preLoaderRoute: typeof HousekeepingRoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/front-office/tasks': {
      id: '/front-office/tasks'
      path: '/front-office/tasks'
      fullPath: '/front-office/tasks'
      preLoaderRoute: typeof FrontOfficeTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/front-office/conversations': {
      id: '/front-office/conversations'
      path: '/front-office/conversations'
      fullPath: '/front-office/conversations'
      preLoaderRoute: typeof FrontOfficeConversationsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  FrontOfficeConversationsRoute: FrontOfficeConversationsRoute,
  FrontOfficeTasksRoute: FrontOfficeTasksRoute,
  HousekeepingRoomsRoute: HousekeepingRoomsRoute,
  HousekeepingTasksRoute: HousekeepingTasksRoute,
  MaintenanceIssuesRoute: MaintenanceIssuesRoute,
  MaintenanceTasksRoute: MaintenanceTasksRoute,
  ManagerConversationsRoute: ManagerConversationsRoute,
  ManagerSettingsRoute: ManagerSettingsRoute,
  ManagerTasksRoute: ManagerTasksRoute,
  ManagerUpsellsRoute: ManagerUpsellsRoute,
  FrontOfficeIndexRoute: FrontOfficeIndexRoute,
  HousekeepingIndexRoute: HousekeepingIndexRoute,
  MaintenanceIndexRoute: MaintenanceIndexRoute,
  ManagerIndexRoute: ManagerIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
